<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ExtremeEditor.AssetExtractor.Tests</AssemblyName>
    <RootNamespace>ExtremeEditor.AssetExtractor.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExtremeEditor.AssetExtractor\ExtremeEditor.AssetExtractor.csproj" />
  </ItemGroup>
</Project>
