<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExtremeEditor.Core\ExtremeEditor.Core.csproj" />
    <ProjectReference Include="..\ExtremeEditor.Rendering\ExtremeEditor.Rendering.csproj" />
    <ProjectReference Include="..\ExtremeEditor.Audio\ExtremeEditor.Audio.csproj" />
  </ItemGroup>
</Project>
